--------------------------------------------------------
-- Archivo creado  - viernes-agosto-07-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_ACCIDENTE
--------------------------------------------------------

   CREATE SEQUENCE  "USUARIO_PRUEBA5"."SEQ_ACCIDENTE"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CLIENTE
--------------------------------------------------------

   CREATE SEQUENCE  "USUARIO_PRUEBA5"."SEQ_CLIENTE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PERSONA
--------------------------------------------------------

   CREATE SEQUENCE  "USUARIO_PRUEBA5"."SEQ_PERSONA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ACCIDENTE
--------------------------------------------------------

  CREATE TABLE "USUARIO_PRUEBA5"."ACCIDENTE" 
   (	"ID_ACCIDENTE" NUMBER(*,0), 
	"PERSONA_ID_PERSONA" NUMBER(*,0), 
	"FECHA_ACCIDENTE" DATE, 
	"LABOR_DESARROLLADA" VARCHAR2(500 BYTE), 
	"CLIENTE_ID_CLIENTE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ACTIVIDAD_MEJORA
--------------------------------------------------------

  CREATE TABLE "USUARIO_PRUEBA5"."ACTIVIDAD_MEJORA" 
   (	"ID_ACTIVIDAD" NUMBER(*,0), 
	"ACTIVIDAD" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ASESORIA
--------------------------------------------------------

  CREATE TABLE "USUARIO_PRUEBA5"."ASESORIA" 
   (	"ID_ASESORIA" NUMBER(*,0), 
	"MOTIVO" VARCHAR2(500 BYTE), 
	"CLIENTE_ID_CLIENTE" NUMBER(*,0), 
	"PERSONA_ID_PERSONA" NUMBER(*,0), 
	"FECHA" DATE, 
	"HORA" DATE, 
	"ACCIDENTE_ID_ACCIDENTE" NUMBER(*,0), 
	"OK" CHAR(1 BYTE), 
	"ATRASO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AUTHORITIES
--------------------------------------------------------

  CREATE TABLE "USUARIO_PRUEBA5"."AUTHORITIES" 
   (	"ID_ROL" NUMBER(*,0), 
	"USERNAME" VARCHAR2(30 BYTE), 
	"AUTHORITY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CAPACITACION
--------------------------------------------------------

  CREATE TABLE "USUARIO_PRUEBA5"."CAPACITACION" 
   (	"ID_CAOACITACION" NUMBER(*,0), 
	"OBJETIVO" VARCHAR2(1000 BYTE), 
	"NUM_ASISTENTES" NUMBER(*,0), 
	"PERSONA_ID_PERSONA" NUMBER(*,0), 
	"CLIENTE_ID_CLIENTE" NUMBER(*,0), 
	"FECHA" DATE, 
	"HORA" DATE, 
	"DURACION" VARCHAR2(100 BYTE), 
	"OK" CHAR(1 BYTE), 
	"ATRASO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHECK
--------------------------------------------------------

  CREATE TABLE "USUARIO_PRUEBA5"."CHECK" 
   (	"ID_ACCION" NUMBER(*,0), 
	"ACCION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHECKLIST
--------------------------------------------------------

  CREATE TABLE "USUARIO_PRUEBA5"."CHECKLIST" 
   (	"CLIENTE_ID_CLIENTE" NUMBER(*,0), 
	"CHECK_ID_ACCION" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "USUARIO_PRUEBA5"."CLIENTE" 
   (	"ID_CLIENTE" NUMBER(*,0), 
	"RAZON_SOCIAL" VARCHAR2(200 BYTE), 
	"RUT" VARCHAR2(12 BYTE), 
	"RUBRO" VARCHAR2(200 BYTE), 
	"DIRECCION" VARCHAR2(500 BYTE), 
	"COMUNA_ID_COMUNA" NUMBER(*,0), 
	"NUM_COLABORADORES" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMUNA
--------------------------------------------------------

  CREATE TABLE "USUARIO_PRUEBA5"."COMUNA" 
   (	"ID_COMUNA" NUMBER(*,0), 
	"COMUNA" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LISTA_MEJORAS
--------------------------------------------------------

  CREATE TABLE "USUARIO_PRUEBA5"."LISTA_MEJORAS" 
   (	"CLIENTE_ID_CLIENTE" NUMBER(*,0), 
	"ACT_MEJORA_ID_ACTIVIDAD" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONA
--------------------------------------------------------

  CREATE TABLE "USUARIO_PRUEBA5"."PERSONA" 
   (	"ID_PERSONA" NUMBER(*,0), 
	"RUT" VARCHAR2(12 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"APELLIDO_PATERNO" VARCHAR2(100 BYTE), 
	"APELLIDO_MATERNO" VARCHAR2(100 BYTE), 
	"EDAD" NUMBER(*,0), 
	"ES_PROFESIONAL" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "USUARIO_PRUEBA5"."USERS" 
   (	"ID_USER" NUMBER(*,0), 
	"USERNAME" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"ENABLED" CHAR(1 BYTE) DEFAULT '1', 
	"CLIENTE_ID_CLIENTE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into USUARIO_PRUEBA5.ACCIDENTE
SET DEFINE OFF;
Insert into USUARIO_PRUEBA5.ACCIDENTE (ID_ACCIDENTE,PERSONA_ID_PERSONA,FECHA_ACCIDENTE,LABOR_DESARROLLADA,CLIENTE_ID_CLIENTE) values ('21','2',to_date('22/04/20','DD/MM/RR'),'JUGANDO','2');
REM INSERTING into USUARIO_PRUEBA5.ACTIVIDAD_MEJORA
SET DEFINE OFF;
REM INSERTING into USUARIO_PRUEBA5.ASESORIA
SET DEFINE OFF;
REM INSERTING into USUARIO_PRUEBA5.AUTHORITIES
SET DEFINE OFF;
Insert into USUARIO_PRUEBA5.AUTHORITIES (ID_ROL,USERNAME,AUTHORITY) values ('1','admin','ADMIN');
Insert into USUARIO_PRUEBA5.AUTHORITIES (ID_ROL,USERNAME,AUTHORITY) values ('2','cliente1','CLIENTE');
Insert into USUARIO_PRUEBA5.AUTHORITIES (ID_ROL,USERNAME,AUTHORITY) values ('3','cliente2','CLIENTE');
REM INSERTING into USUARIO_PRUEBA5.CAPACITACION
SET DEFINE OFF;
REM INSERTING into USUARIO_PRUEBA5."CHECK"
SET DEFINE OFF;
REM INSERTING into USUARIO_PRUEBA5.CHECKLIST
SET DEFINE OFF;
REM INSERTING into USUARIO_PRUEBA5.CLIENTE
SET DEFINE OFF;
Insert into USUARIO_PRUEBA5.CLIENTE (ID_CLIENTE,RAZON_SOCIAL,RUT,RUBRO,DIRECCION,COMUNA_ID_COMUNA,NUM_COLABORADORES) values ('2','Compuglobalhipermeganet11','111111','tecnologia111','calle 555111','1','11');
Insert into USUARIO_PRUEBA5.CLIENTE (ID_CLIENTE,RAZON_SOCIAL,RUT,RUBRO,DIRECCION,COMUNA_ID_COMUNA,NUM_COLABORADORES) values ('3','cliente2','123456-7','tecnologia','sdds','5','1');
REM INSERTING into USUARIO_PRUEBA5.COMUNA
SET DEFINE OFF;
Insert into USUARIO_PRUEBA5.COMUNA (ID_COMUNA,COMUNA) values ('1','Santiago');
Insert into USUARIO_PRUEBA5.COMUNA (ID_COMUNA,COMUNA) values ('2','La Florida');
Insert into USUARIO_PRUEBA5.COMUNA (ID_COMUNA,COMUNA) values ('3','Puente Alto');
Insert into USUARIO_PRUEBA5.COMUNA (ID_COMUNA,COMUNA) values ('4','Estacion Central');
Insert into USUARIO_PRUEBA5.COMUNA (ID_COMUNA,COMUNA) values ('5','Maipu');
Insert into USUARIO_PRUEBA5.COMUNA (ID_COMUNA,COMUNA) values ('6','La Pintana');
REM INSERTING into USUARIO_PRUEBA5.LISTA_MEJORAS
SET DEFINE OFF;
REM INSERTING into USUARIO_PRUEBA5.PERSONA
SET DEFINE OFF;
Insert into USUARIO_PRUEBA5.PERSONA (ID_PERSONA,RUT,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,EDAD,ES_PROFESIONAL) values ('1','11111111111','sdfdsf','quidsvsv','mellsczxcz','70','1');
Insert into USUARIO_PRUEBA5.PERSONA (ID_PERSONA,RUT,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,EDAD,ES_PROFESIONAL) values ('2','11111111','tes persona','test','test','50','0');
Insert into USUARIO_PRUEBA5.PERSONA (ID_PERSONA,RUT,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,EDAD,ES_PROFESIONAL) values ('3','111111','persona','ap','ap','55','0');
Insert into USUARIO_PRUEBA5.PERSONA (ID_PERSONA,RUT,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,EDAD,ES_PROFESIONAL) values ('200','18610198-7','Fer','test','test','27','0');
Insert into USUARIO_PRUEBA5.PERSONA (ID_PERSONA,RUT,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,EDAD,ES_PROFESIONAL) values ('250','18610198-7','fer','fer','fer','10','0');
REM INSERTING into USUARIO_PRUEBA5.USERS
SET DEFINE OFF;
Insert into USUARIO_PRUEBA5.USERS (ID_USER,USERNAME,PASSWORD,ENABLED,CLIENTE_ID_CLIENTE) values ('1','admin','$2a$10$yfANWcOASEsqC1eRfqCGbu4izWXWRNsblNBy4j1x9MGFQX251obva','1',null);
Insert into USUARIO_PRUEBA5.USERS (ID_USER,USERNAME,PASSWORD,ENABLED,CLIENTE_ID_CLIENTE) values ('2','cliente1','$2a$10$IwpMVczGnMYLz.OSveaWqODU7fHcJsXrymyFp18lDhk/XWbFDMqEG','1','2');
Insert into USUARIO_PRUEBA5.USERS (ID_USER,USERNAME,PASSWORD,ENABLED,CLIENTE_ID_CLIENTE) values ('3','cliente2','$2a$10$IwpMVczGnMYLz.OSveaWqODU7fHcJsXrymyFp18lDhk/XWbFDMqEG','1',null);
--------------------------------------------------------
--  DDL for Index PERSONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIO_PRUEBA5"."PERSONA_PK" ON "USUARIO_PRUEBA5"."PERSONA" ("ID_PERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ASESORIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIO_PRUEBA5"."ASESORIA_PK" ON "USUARIO_PRUEBA5"."ASESORIA" ("ID_ASESORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CAPACITACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIO_PRUEBA5"."CAPACITACION_PK" ON "USUARIO_PRUEBA5"."CAPACITACION" ("ID_CAOACITACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CHECKLIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIO_PRUEBA5"."CHECKLIST_PK" ON "USUARIO_PRUEBA5"."CHECKLIST" ("CLIENTE_ID_CLIENTE", "CHECK_ID_ACCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ASESORIA__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIO_PRUEBA5"."ASESORIA__IDX" ON "USUARIO_PRUEBA5"."ASESORIA" ("ACCIDENTE_ID_ACCIDENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CHECK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIO_PRUEBA5"."CHECK_PK" ON "USUARIO_PRUEBA5"."CHECK" ("ID_ACCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMUNA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIO_PRUEBA5"."COMUNA_PK" ON "USUARIO_PRUEBA5"."COMUNA" ("ID_COMUNA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LISTA_MEJORAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIO_PRUEBA5"."LISTA_MEJORAS_PK" ON "USUARIO_PRUEBA5"."LISTA_MEJORAS" ("CLIENTE_ID_CLIENTE", "ACT_MEJORA_ID_ACTIVIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIO_PRUEBA5"."CLIENTE_PK" ON "USUARIO_PRUEBA5"."CLIENTE" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ACT_MEJORA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIO_PRUEBA5"."ACT_MEJORA_PK" ON "USUARIO_PRUEBA5"."ACTIVIDAD_MEJORA" ("ID_ACTIVIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AUTHORITIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIO_PRUEBA5"."AUTHORITIES_PK" ON "USUARIO_PRUEBA5"."AUTHORITIES" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ACCIDENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIO_PRUEBA5"."ACCIDENTE_PK" ON "USUARIO_PRUEBA5"."ACCIDENTE" ("ID_ACCIDENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIO_PRUEBA5"."USERS_PK" ON "USUARIO_PRUEBA5"."USERS" ("ID_USER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "USUARIO_PRUEBA5"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USUARIO_PRUEBA5"."CLIENTE" MODIFY ("COMUNA_ID_COMUNA" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_PRUEBA5"."CLIENTE" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_PRUEBA5"."CLIENTE" MODIFY ("RAZON_SOCIAL" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_PRUEBA5"."CLIENTE" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACTIVIDAD_MEJORA
--------------------------------------------------------

  ALTER TABLE "USUARIO_PRUEBA5"."ACTIVIDAD_MEJORA" ADD CONSTRAINT "ACT_MEJORA_PK" PRIMARY KEY ("ID_ACTIVIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USUARIO_PRUEBA5"."ACTIVIDAD_MEJORA" MODIFY ("ID_ACTIVIDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "USUARIO_PRUEBA5"."PERSONA" ADD CONSTRAINT "PERSONA_PK" PRIMARY KEY ("ID_PERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USUARIO_PRUEBA5"."PERSONA" MODIFY ("ES_PROFESIONAL" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_PRUEBA5"."PERSONA" MODIFY ("RUT" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_PRUEBA5"."PERSONA" MODIFY ("ID_PERSONA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACCIDENTE
--------------------------------------------------------

  ALTER TABLE "USUARIO_PRUEBA5"."ACCIDENTE" ADD CONSTRAINT "ACCIDENTE_PK" PRIMARY KEY ("ID_ACCIDENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USUARIO_PRUEBA5"."ACCIDENTE" MODIFY ("CLIENTE_ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_PRUEBA5"."ACCIDENTE" MODIFY ("LABOR_DESARROLLADA" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_PRUEBA5"."ACCIDENTE" MODIFY ("FECHA_ACCIDENTE" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_PRUEBA5"."ACCIDENTE" MODIFY ("PERSONA_ID_PERSONA" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_PRUEBA5"."ACCIDENTE" MODIFY ("ID_ACCIDENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHECKLIST
--------------------------------------------------------

  ALTER TABLE "USUARIO_PRUEBA5"."CHECKLIST" ADD CONSTRAINT "CHECKLIST_PK" PRIMARY KEY ("CLIENTE_ID_CLIENTE", "CHECK_ID_ACCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USUARIO_PRUEBA5"."CHECKLIST" MODIFY ("CHECK_ID_ACCION" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_PRUEBA5"."CHECKLIST" MODIFY ("CLIENTE_ID_CLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTHORITIES
--------------------------------------------------------

  ALTER TABLE "USUARIO_PRUEBA5"."AUTHORITIES" ADD CONSTRAINT "AUTHORITIES_PK" PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USUARIO_PRUEBA5"."AUTHORITIES" MODIFY ("ID_ROL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LISTA_MEJORAS
--------------------------------------------------------

  ALTER TABLE "USUARIO_PRUEBA5"."LISTA_MEJORAS" ADD CONSTRAINT "LISTA_MEJORAS_PK" PRIMARY KEY ("CLIENTE_ID_CLIENTE", "ACT_MEJORA_ID_ACTIVIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USUARIO_PRUEBA5"."LISTA_MEJORAS" MODIFY ("ACT_MEJORA_ID_ACTIVIDAD" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_PRUEBA5"."LISTA_MEJORAS" MODIFY ("CLIENTE_ID_CLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASESORIA
--------------------------------------------------------

  ALTER TABLE "USUARIO_PRUEBA5"."ASESORIA" ADD CONSTRAINT "ASESORIA_PK" PRIMARY KEY ("ID_ASESORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USUARIO_PRUEBA5"."ASESORIA" MODIFY ("PERSONA_ID_PERSONA" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_PRUEBA5"."ASESORIA" MODIFY ("CLIENTE_ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_PRUEBA5"."ASESORIA" MODIFY ("MOTIVO" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_PRUEBA5"."ASESORIA" MODIFY ("ID_ASESORIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "USUARIO_PRUEBA5"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("ID_USER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USUARIO_PRUEBA5"."USERS" MODIFY ("ID_USER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMUNA
--------------------------------------------------------

  ALTER TABLE "USUARIO_PRUEBA5"."COMUNA" ADD CONSTRAINT "COMUNA_PK" PRIMARY KEY ("ID_COMUNA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USUARIO_PRUEBA5"."COMUNA" MODIFY ("COMUNA" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_PRUEBA5"."COMUNA" MODIFY ("ID_COMUNA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHECK
--------------------------------------------------------

  ALTER TABLE "USUARIO_PRUEBA5"."CHECK" ADD CONSTRAINT "CHECK_PK" PRIMARY KEY ("ID_ACCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USUARIO_PRUEBA5"."CHECK" MODIFY ("ACCION" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_PRUEBA5"."CHECK" MODIFY ("ID_ACCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CAPACITACION
--------------------------------------------------------

  ALTER TABLE "USUARIO_PRUEBA5"."CAPACITACION" ADD CONSTRAINT "CAPACITACION_PK" PRIMARY KEY ("ID_CAOACITACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USUARIO_PRUEBA5"."CAPACITACION" MODIFY ("CLIENTE_ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_PRUEBA5"."CAPACITACION" MODIFY ("PERSONA_ID_PERSONA" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_PRUEBA5"."CAPACITACION" MODIFY ("NUM_ASISTENTES" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_PRUEBA5"."CAPACITACION" MODIFY ("OBJETIVO" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_PRUEBA5"."CAPACITACION" MODIFY ("ID_CAOACITACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACCIDENTE
--------------------------------------------------------

  ALTER TABLE "USUARIO_PRUEBA5"."ACCIDENTE" ADD CONSTRAINT "ACCIDENTE_CLIENTE_FK" FOREIGN KEY ("CLIENTE_ID_CLIENTE")
	  REFERENCES "USUARIO_PRUEBA5"."CLIENTE" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "USUARIO_PRUEBA5"."ACCIDENTE" ADD CONSTRAINT "ACCIDENTE_PERSONA_FK" FOREIGN KEY ("PERSONA_ID_PERSONA")
	  REFERENCES "USUARIO_PRUEBA5"."PERSONA" ("ID_PERSONA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASESORIA
--------------------------------------------------------

  ALTER TABLE "USUARIO_PRUEBA5"."ASESORIA" ADD CONSTRAINT "ASESORIA_ACCIDENTE_FK" FOREIGN KEY ("ACCIDENTE_ID_ACCIDENTE")
	  REFERENCES "USUARIO_PRUEBA5"."ACCIDENTE" ("ID_ACCIDENTE") ENABLE;
  ALTER TABLE "USUARIO_PRUEBA5"."ASESORIA" ADD CONSTRAINT "ASESORIA_CLIENTE_FK" FOREIGN KEY ("CLIENTE_ID_CLIENTE")
	  REFERENCES "USUARIO_PRUEBA5"."CLIENTE" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "USUARIO_PRUEBA5"."ASESORIA" ADD CONSTRAINT "ASESORIA_PERSONA_FK" FOREIGN KEY ("PERSONA_ID_PERSONA")
	  REFERENCES "USUARIO_PRUEBA5"."PERSONA" ("ID_PERSONA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CAPACITACION
--------------------------------------------------------

  ALTER TABLE "USUARIO_PRUEBA5"."CAPACITACION" ADD CONSTRAINT "CAPACITACION_CLIENTE_FK" FOREIGN KEY ("CLIENTE_ID_CLIENTE")
	  REFERENCES "USUARIO_PRUEBA5"."CLIENTE" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "USUARIO_PRUEBA5"."CAPACITACION" ADD CONSTRAINT "CAPACITACION_PERSONA_FK" FOREIGN KEY ("PERSONA_ID_PERSONA")
	  REFERENCES "USUARIO_PRUEBA5"."PERSONA" ("ID_PERSONA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHECKLIST
--------------------------------------------------------

  ALTER TABLE "USUARIO_PRUEBA5"."CHECKLIST" ADD CONSTRAINT "CHECKLIST_CHECK_FK" FOREIGN KEY ("CHECK_ID_ACCION")
	  REFERENCES "USUARIO_PRUEBA5"."CHECK" ("ID_ACCION") ENABLE;
  ALTER TABLE "USUARIO_PRUEBA5"."CHECKLIST" ADD CONSTRAINT "CHECKLIST_CLIENTE_FK" FOREIGN KEY ("CLIENTE_ID_CLIENTE")
	  REFERENCES "USUARIO_PRUEBA5"."CLIENTE" ("ID_CLIENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "USUARIO_PRUEBA5"."CLIENTE" ADD CONSTRAINT "CLIENTE_COMUNA_FK" FOREIGN KEY ("COMUNA_ID_COMUNA")
	  REFERENCES "USUARIO_PRUEBA5"."COMUNA" ("ID_COMUNA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LISTA_MEJORAS
--------------------------------------------------------

  ALTER TABLE "USUARIO_PRUEBA5"."LISTA_MEJORAS" ADD CONSTRAINT "LISTA_MEJORAS_CLIENTE_FK" FOREIGN KEY ("CLIENTE_ID_CLIENTE")
	  REFERENCES "USUARIO_PRUEBA5"."CLIENTE" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "USUARIO_PRUEBA5"."LISTA_MEJORAS" ADD CONSTRAINT "LIST_MEJORAS_ACT_MEJORA_FK" FOREIGN KEY ("ACT_MEJORA_ID_ACTIVIDAD")
	  REFERENCES "USUARIO_PRUEBA5"."ACTIVIDAD_MEJORA" ("ID_ACTIVIDAD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "USUARIO_PRUEBA5"."USERS" ADD CONSTRAINT "USERS_CLIENTE_FK" FOREIGN KEY ("CLIENTE_ID_CLIENTE")
	  REFERENCES "USUARIO_PRUEBA5"."CLIENTE" ("ID_CLIENTE") ENABLE;
